#!/bin/sh

# Ensure that all zip codes in our data are JSON strings.
#
# The original us_addresses.json data represents zip codes that start
# with 0 as strings and all other zip codes as numbers, e.g.,
#
#    "zip":"00601"  ...but...
#    "zip":59115
#
# This script ensures that they're all strings, to avoid insanity.

for name in us_addresses.json us_addresses_*.json; do
    sed -e 's/{"zip":\([0-9][0-9][0-9][0-9][0-9]\),/{"zip":"\1",/' < ${name} > tmp_${name}
    mv tmp_${name} ${name}
done
