#!/bin/sh

# Ensure that all zip codes in our data are JSON strings.
#
# The original us_addresses.json data represents zip codes that start
# with 0 as strings and all other zip codes as numbers, e.g.,
#
#    "zip":"00601"  ...but...
#    "zip":59115
#
# This script ensures that they're all strings, to avoid insanity.

sed -e 's/{"zip":\([0-9][0-9][0-9][0-9][0-9]\),/{"zip":"\1",/' \
  < us_addresses.json > tmp_us_addresses.json

mv tmp_us_addresses.json us_addresses.json
